# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class UiPlusWindow(object):
    def __init__(self):
        self.spacer_add_right = None
        self.spacer_add_left = None
        self.button_add = None
        self.horizontal_layout_add = None
        self.vertical_layout_add = None
        self.status_combo_box = None
        self.rating_from = None
        self.rating_spin_box = None
        self.status_text = None
        self.rating_text = None
        self.r1 = None
        self.r2 = None
        self.r3 = None
        self.r4 = None
        self.r5 = None
        self.r6 = None
        self.r7 = None
        self.r8 = None
        self.r9 = None
        self.grid_layout_types = None
        self.horizontal_layout_rating_status = None
        self.vertical_layout_right = None
        self.comment_input = None
        self.input_comment_text = None
        self.horizontal_layout_comment = None
        self.title_input = None
        self.title_text = None
        self.horizontal_layout_title = None
        self.vertical_layout_left = None
        self.back_button = None
        self.grid_layout_left = None
        self.grid_layout_central = None
        self.central_widget = None

    def setupUi(self, main_win):
        main_win.setObjectName("MainWindow")
        main_win.resize(770, 203)
        main_win.setStyleSheet("background-color: rgb(241, 231, 255);")
        self.central_widget = QtWidgets.QWidget(main_win)
        self.grid_layout_central = QtWidgets.QGridLayout(self.central_widget)
        self.grid_layout_left = QtWidgets.QGridLayout()
        self.vertical_layout_left = QtWidgets.QVBoxLayout()
        self.horizontal_layout_title = QtWidgets.QHBoxLayout()
        self.back_button = QtWidgets.QPushButton(self.central_widget)
        self.back_button.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(230, 208, 255);\n"
                                       "    border-radius: 15px;\n"
                                       "    padding: 5px;\n"
                                       "    width: 20px;\n"
                                       "    height: 20px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(157, 0, 255);\n"
                                       "}")
        self.back_button.setObjectName("back_button")
        self.horizontal_layout_title.addWidget(self.back_button)
        self.title_text = QtWidgets.QLabel(self.central_widget)
        self.horizontal_layout_title.addWidget(self.title_text)
        self.title_input = QtWidgets.QLineEdit(self.central_widget)
        self.title_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontal_layout_title.addWidget(self.title_input)
        self.vertical_layout_left.addLayout(self.horizontal_layout_title)
        spacer_item = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.vertical_layout_left.addItem(spacer_item)
        self.horizontal_layout_comment = QtWidgets.QHBoxLayout()
        self.input_comment_text = QtWidgets.QLabel(self.central_widget)
        self.horizontal_layout_comment.addWidget(self.input_comment_text)
        self.comment_input = QtWidgets.QPlainTextEdit(self.central_widget)
        self.comment_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontal_layout_comment.addWidget(self.comment_input)
        self.vertical_layout_left.addLayout(self.horizontal_layout_comment)
        self.grid_layout_left.addLayout(self.vertical_layout_left, 0, 0, 1, 1)
        self.vertical_layout_right = QtWidgets.QVBoxLayout()
        self.grid_layout_types = QtWidgets.QGridLayout()
        self.r1 = QtWidgets.QRadioButton(self.central_widget)
        self.r2 = QtWidgets.QRadioButton(self.central_widget)
        self.r3 = QtWidgets.QRadioButton(self.central_widget)
        self.r4 = QtWidgets.QRadioButton(self.central_widget)
        self.r5 = QtWidgets.QRadioButton(self.central_widget)
        self.r6 = QtWidgets.QRadioButton(self.central_widget)
        self.r7 = QtWidgets.QRadioButton(self.central_widget)
        self.r8 = QtWidgets.QRadioButton(self.central_widget)
        self.r9 = QtWidgets.QRadioButton(self.central_widget)
        check_buttons = [self.r1, self.r2, self.r3, self.r4, self.r5, self.r6, self.r7, self.r8, self.r9]
        for btn_num in range(9):
            check_buttons[btn_num].setStyleSheet("QRadioButton{\n"
                                                 "    background-color: rgb(241, 231, 255);\n"
                                                 "    border-radius: 10px;\n"
                                                 "    padding: 5px;\n"
                                                 "    width: 70px;\n"
                                                 "    height: 15px;\n"
                                                 "}\n"
                                                 "QRadioButton:hover{\n"
                                                 "    background-color: rgb(255, 148, 218);\n"
                                                 "}")

        self.grid_layout_types.addWidget(self.r1, 0, 0, 1, 1)
        self.grid_layout_types.addWidget(self.r2, 0, 1, 1, 1)
        self.grid_layout_types.addWidget(self.r3, 0, 2, 1, 1)
        self.grid_layout_types.addWidget(self.r4, 1, 0, 1, 1)
        self.grid_layout_types.addWidget(self.r5, 1, 1, 1, 1)
        self.grid_layout_types.addWidget(self.r6, 1, 2, 1, 1)
        self.grid_layout_types.addWidget(self.r7, 2, 0, 1, 1)
        self.grid_layout_types.addWidget(self.r8, 2, 1, 1, 1)
        self.grid_layout_types.addWidget(self.r9, 2, 2, 1, 1)

        self.vertical_layout_right.addLayout(self.grid_layout_types)

        self.horizontal_layout_rating_status = QtWidgets.QHBoxLayout()
        self.rating_text = QtWidgets.QLabel(self.central_widget)
        self.horizontal_layout_rating_status.addWidget(self.rating_text)
        self.rating_spin_box = QtWidgets.QSpinBox(self.central_widget)
        self.rating_spin_box.setStyleSheet("QSpinBox{\n"
                                           "    background-color: rgb(230, 208, 255);\n"
                                           "    border-radius: 10px;\n"
                                           "    padding: 5px;\n"
                                           "    width: 20px;\n"
                                           "    height: 15px;\n"
                                           "}\n"
                                           "QSpinBox:hover{\n"
                                           "    background-color: rgb(157, 0, 255);\n"
                                           "}")
        self.horizontal_layout_rating_status.addWidget(self.rating_spin_box)
        self.rating_from = QtWidgets.QLabel(self.central_widget)
        self.horizontal_layout_rating_status.addWidget(self.rating_from)
        self.status_text = QtWidgets.QLabel(self.central_widget)
        self.horizontal_layout_rating_status.addWidget(self.status_text)
        self.status_combo_box = QtWidgets.QComboBox(self.central_widget)
        self.status_combo_box.setStyleSheet("QComboBox{\n"
                                            "    background-color: rgb(230, 208, 255);\n"
                                            "    border-radius: 10px;\n"
                                            "    padding: 5px;\n"
                                            "    width: 80px;\n"
                                            "    height: 15px;\n"
                                            "}\n"
                                            "QComboBox:hover{\n"
                                            "    background-color: rgb(157, 0, 255);\n"
                                            "}")
        self.status_combo_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.status_combo_box.addItem("")
        self.horizontal_layout_rating_status.addWidget(self.status_combo_box)
        self.vertical_layout_right.addLayout(self.horizontal_layout_rating_status)
        self.vertical_layout_add = QtWidgets.QVBoxLayout()
        self.horizontal_layout_add = QtWidgets.QHBoxLayout()
        self.button_add = QtWidgets.QPushButton(self.central_widget)
        self.button_add.setStyleSheet("QPushButton{\n"
                                      "    background-color: rgb(230, 208, 255);\n"
                                      "    border-radius: 10px;\n"
                                      "    padding: 5px;\n"
                                      "    width: 60px;\n"
                                      "    height: 15px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(157, 0, 255);\n"
                                      "}")
        #self.button_add.setObjectName("btnadd")

        self.spacer_add_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                                     QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontal_layout_add.addItem(self.spacer_add_left)
        self.horizontal_layout_add.addWidget(self.button_add)
        self.spacer_add_right = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                                      QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontal_layout_add.addItem(self.spacer_add_right)
        self.vertical_layout_add.addLayout(self.horizontal_layout_add)
        self.vertical_layout_right.addLayout(self.vertical_layout_add)
        self.grid_layout_left.addLayout(self.vertical_layout_right, 0, 1, 1, 1)
        self.grid_layout_central.addLayout(self.grid_layout_left, 0, 0, 1, 1)
        main_win.setCentralWidget(self.central_widget)

        self.translate_ui(main_win)
        QtCore.QMetaObject.connectSlotsByName(main_win)

    def translate_ui(self, main_win):
        _translate = QtCore.QCoreApplication.translate
        main_win.setWindowTitle(_translate("MainWindow", "add title"))
        self.back_button.setText(_translate("MainWindow", "<-"))
        self.title_text.setText(_translate("MainWindow", " title:\t"))
        self.input_comment_text.setText(_translate("MainWindow", "input comment:\t"))
        self.r2.setText(_translate("MainWindow", "book"))
        self.r1.setText(_translate("MainWindow", "film"))
        self.r8.setText(_translate("MainWindow", "comic strip"))
        self.r9.setText(_translate("MainWindow", "cartoon"))
        self.r4.setText(_translate("MainWindow", "anime"))
        self.r6.setText(_translate("MainWindow", "manhua"))
        self.r7.setText(_translate("MainWindow", "series"))
        self.r3.setText(_translate("MainWindow", "manhwa"))
        self.r5.setText(_translate("MainWindow", "manga"))
        self.rating_text.setText(_translate("MainWindow", "  rating:"))
        self.rating_from.setText(_translate("MainWindow", "/10"))
        self.status_text.setText(_translate("MainWindow", "input status:"))
        self.status_combo_box.setItemText(0, _translate("MainWindow", "planned"))
        self.status_combo_box.setItemText(1, _translate("MainWindow", "in progress"))
        self.status_combo_box.setItemText(2, _translate("MainWindow", "finished"))
        self.button_add.setText(_translate("MainWindow", "add"))
