# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class UiAddFromSearchWindow(object):
    def __init__(self):
        self.back_button = None
        self.verticalLayout_2 = None
        self.horizontalLayout_3 = None
        self.gridLayout_2 = None
        self.central_widget = None
        self.gridLayout_3 = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(770, 203)
        MainWindow.setStyleSheet("background-color: rgb(241, 231, 255);")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.gridLayout_3 = QtWidgets.QGridLayout(self.central_widget)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.back_button = QtWidgets.QPushButton(self.central_widget)
        self.back_button.setStyleSheet("QPushButton{\n"
                                       "    background-color: rgb(230, 208, 255);\n"
                                       "    border-radius: 15px;\n"
                                       "    padding: 5px;\n"
                                       "    width: 20px;\n"
                                       "    height: 20px;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "    background-color: rgb(157, 0, 255);\n"
                                       "}")
        self.horizontalLayout_3.addWidget(self.back_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.comment_text = QtWidgets.QLabel(self.central_widget)
        self.horizontalLayout_4.addWidget(self.comment_text)
        self.comment_input = QtWidgets.QPlainTextEdit(self.central_widget)
        self.comment_input.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.horizontalLayout_4.addWidget(self.comment_input)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.rating_spin_box = QtWidgets.QSpinBox(self.central_widget)
        self.rating_spin_box.setStyleSheet("QSpinBox{\n"
                                           "    background-color: rgb(230, 208, 255);\n"
                                           "    border-radius: 10px;\n"
                                           "    padding: 5px;\n"
                                           "    width: 20px;\n"
                                           "    height: 15px;\n"
                                           "}\n"
                                           "QSpinBox:hover{\n"
                                           "    background-color: rgb(157, 0, 255);\n"
                                           "}")
        self.horizontalLayout.addWidget(self.rating_spin_box)
        self.label_2 = QtWidgets.QLabel(self.central_widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.central_widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.status_box = QtWidgets.QComboBox(self.central_widget)
        self.status_box.setStyleSheet("QComboBox{\n"
                                      "    background-color: rgb(230, 208, 255);\n"
                                      "    border-radius: 10px;\n"
                                      "    padding: 5px;\n"
                                      "    width: 80px;\n"
                                      "    height: 15px;\n"
                                      "}\n"
                                      "QComboBox:hover{\n"
                                      "    background-color: rgb(157, 0, 255);\n"
                                      "}")
        self.status_box.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContents)
        self.status_box.setObjectName("statusbox")
        self.status_box.addItem("")
        self.status_box.addItem("")
        self.status_box.addItem("")
        self.horizontalLayout.addWidget(self.status_box)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.button_add = QtWidgets.QPushButton(self.central_widget)
        self.button_add.setStyleSheet("QPushButton{\n"
                                      "    background-color: rgb(230, 208, 255);\n"
                                      "    border-radius: 10px;\n"
                                      "    padding: 5px;\n"
                                      "    width: 60px;\n"
                                      "    height: 15px;\n"
                                      "}\n"
                                      "QPushButton:hover{\n"
                                      "    background-color: rgb(157, 0, 255);\n"
                                      "}")
        self.button_add.setObjectName("btnadd")
        self.horizontalLayout_2.addWidget(self.button_add)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "add title"))
        self.back_button.setText(_translate("MainWindow", "<-"))
        self.comment_text.setText(_translate("MainWindow", "comment: "))
        self.label.setText(_translate("MainWindow", "rating"))
        self.label_2.setText(_translate("MainWindow", "/10          "))
        self.label_5.setText(_translate("MainWindow", "status"))
        self.status_box.setItemText(0, _translate("MainWindow", "planned"))
        self.status_box.setItemText(1, _translate("MainWindow", "progress"))
        self.status_box.setItemText(2, _translate("MainWindow", "finished"))
        self.button_add.setText(_translate("MainWindow", "add"))
